[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[profile.default]
  src = 'contracts'
  out = 'out'
  libs = ['node_modules', 'lib']
  test = 'test'
  cache_path  = 'cache_forge'
  solc = "0.8.24"
  optimizer = true
  optimizer_runs = 10_000
  gas_reports = ["*"]
  fuzz = { runs = 1_000 }
  auto_detect_solc = false
  extra_output_files = [ "metadata" ]
  viaIR = true

[dependencies]
  "@openzeppelin-contracts" = "5.0.2"
