import { SettleMintProvider } from "@settlemint/sdk-react";
import { QueryClient } from "@tanstack/react-query";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create SettleMint App",
  description: "Generated by the SettleMint SDK",
};

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SettleMintProvider client={queryClient}>
        <body className={inter.className}>{children}</body>
      </SettleMintProvider>
    </html>
  );
}
