on:
  schedule:
    - cron: '0 18 * * *' # runs every day at 6PM UTC
  workflow_dispatch:

name: E2E reset

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  e2e:
    name: E2E reset
    runs-on: namespace-profile-sdk
    steps:
      - name: Setup 1Password
        uses: 1password/load-secrets-action/configure@13f58eec611f8e5db52ec16247f58c508398f3e6 # v3
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Load secrets
        uses: 1password/load-secrets-action@13f58eec611f8e5db52ec16247f58c508398f3e6 # v3
        with:
          export-env: true
        env:
          E2E_GITHUB_TOKEN: "op://platform/SDK E2E/github-token"
          SETTLEMINT_ACCESS_TOKEN_E2E_TESTS: "op://platform/SDK E2E/pat-token"
          SETTLEMINT_INSTANCE: "op://platform/SDK E2E/instance"

      - name: Checkout repository
        uses: namespacelabs/nscloud-checkout-action@953fed31a6113cc2347ca69c9d823743c65bc84b # v7

      - name: Login to SettleMint and delete workspace
        uses: settlemint/settlemint-action@main
        if: ${{ env.SETTLEMINT_WORKSPACE != '' }}
        env:
          SETTLEMINT_WORKSPACE: ${{ secrets.SETTLEMINT_WORKSPACE }}
        with:
          instance: ${{ env.SETTLEMINT_INSTANCE }}
          access-token: ${{ env.SETTLEMINT_ACCESS_TOKEN_E2E_TESTS }}
          auto-connect: false
          workspace: ${{ secrets.SETTLEMINT_WORKSPACE }}
          command: platform delete workspace --accept-defaults --force default

      - name: Delete all secrets
        run: |
          echo $E2E_GITHUB_TOKEN | gh auth login --with-token
          gh secret list | while read -r secret _; do
            gh secret delete "$secret"
          done
        env:
          E2E_GITHUB_TOKEN: ${{ env.E2E_GITHUB_TOKEN }}