on:
  schedule:
    - cron: '0 0 * * *' # runs every night Sun-Fri at 2AM (time difference with GHA! + 2hr)
  workflow_dispatch:

name: E2E

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  e2e:
    name: E2E
    runs-on: namespace-profile-sdk
    steps:
      - name: Checkout repository
        uses: namespacelabs/nscloud-checkout-action@v5

      - name: Setup caches
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            ./.turbo
            ~/.bun/install/cache

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Bun dependencies
        run: bun install

      - name: Run build
        run: bunx turbo build

      - name: Run the E2E tests
        run: bun test:e2e
        env:
          SETTLEMINT_INSTANCE: ${{ secrets.SETTLEMINT_INSTANCE_E2E_TESTS }}
          SETTLEMINT_ACCESS_TOKEN: ${{ secrets.SETTLEMINT_ACCESS_TOKEN_E2E_TESTS }}