on:
  schedule:
    - cron: '0 6 * * 1-5' # runs every morning Mon-Fri at 6AM UTC
  pull_request:
    types: [labeled]
  workflow_dispatch:

name: E2E

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  e2e:
    name: E2E
    timeout-minutes: 60  # Ensures the job never runs longer than 1 hour
    if: ${{ github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'e2e') }}
    runs-on: namespace-profile-sdk
    steps:
      - name: Setup 1Password
        uses: 1password/load-secrets-action/configure@581a835fb51b8e7ec56b71cf2ffddd7e68bb25e0 # v2
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Load secrets
        uses: 1password/load-secrets-action@581a835fb51b8e7ec56b71cf2ffddd7e68bb25e0 # v2
        env:
          E2E_GITHUB_TOKEN: "op://platform/SDK E2E/github-token"
          SETTLEMINT_ACCESS_TOKEN_E2E_TESTS: "op://platform/SDK E2E/pat-token"
          SETTLEMINT_INSTANCE: "op://platform/SDK E2E/instance"
          DISABLE_CONCURRENT_DEPLOYMENT: "op://platform/SDK E2E/disable-concurrent-deployment"

      - name: Checkout repository
        uses: namespacelabs/nscloud-checkout-action@b8c45d632ce8118a5a0a51eb75a57cfccc74b8fa # v5

      - name: Setup caches
        uses: namespacelabs/nscloud-cache-action@f23fbf3b586540a96f4f5849a5e04c7e56e1e804 # v1
        with:
          path: |
            ./.turbo
            ~/.bun/install/cache

      - name: Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version-file: package.json

      - name: Setup git user
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@de808b1eea699e761c404bda44ba8f21aba30b2c # v1

      - name: Get workspace config
        run: |
          echo $ENV_E2E > .env
          echo $ENV_E2E_LOCAL > .env.local
          echo $ENV_E2E
          echo $ENV_E2E_LOCAL
        env:
          ENV_E2E: ${{ secrets.ENV_E2E }}
          ENV_E2E_LOCAL: ${{ secrets.ENV_E2E_LOCAL }}

      - name: Install Bun dependencies
        run: bun install

      - name: Run build
        run: bunx turbo build

      - name: Run the E2E tests
        run: bun test:e2e
        env:
          SETTLEMINT_INSTANCE: ${{ env.SETTLEMINT_INSTANCE }}
          SETTLEMINT_ACCESS_TOKEN_E2E_TESTS: ${{ env.SETTLEMINT_ACCESS_TOKEN_E2E_TESTS }}
          DISABLE_CONCURRENT_DEPLOYMENT: ${{ env.DISABLE_CONCURRENT_DEPLOYMENT }}
          DISABLE_WORKSPACE_DELETE: true

      - name: Get env file
        if: ${{ !cancelled() }}
        id: env-file
        run: echo "ENV_CONTENTS=$(cat .env)" >> $GITHUB_OUTPUT

      - name: Get env.local file
        if: ${{ !cancelled() }}
        id: env-file-local
        run: echo "ENV_LOCAL_CONTENTS=$(cat .env.local)" >> $GITHUB_OUTPUT

      - name: Save workspace config (env)
        if: ${{ !cancelled() }}
        uses: Skandalik/save-secret@v1.0.0
        with:
          github_token: ${{ env.E2E_GITHUB_TOKEN }}
          secret_name: ENV_E2E
          secret_value: ${{ steps.env-file.outputs.ENV_CONTENTS }}

      - name: Save workspace config (env.local)
        if: ${{ !cancelled() }}
        uses: Skandalik/save-secret@v1.0.0
        with:
          github_token: ${{ env.E2E_GITHUB_TOKEN }}
          secret_name: ENV_E2E_LOCAL
          secret_value: ${{ steps.env-file-local.outputs.ENV_LOCAL_CONTENTS }}